# -*- coding: utf-8 -*-
"""Soya beans local price analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ks5OeoDQjrI3RKcyhfg69a863xwU-ILI
"""

import pandas as pd
import matplotlib.pyplot as plt

# Create the dataset
data = {
    "Year": [2020, 2021, 2022],
    "Price_per_KG": [3, 10, 11],
    "Price_per_Bag_50KG": [150, 500, 550],
    "Price_per_MT": [3000, 10000, 11000]
}

df = pd.DataFrame(data)

# FIX: Convert the Year column to string
df["Year"] = df["Year"].astype(str)

df

"""Soya Bean Price per KG (2020–2022)"""

plt.figure(figsize=(8,5))
plt.plot(df["Year"], df["Price_per_KG"], marker="o")
plt.xlabel("Year")
plt.ylabel("Price (ZMW per KG)")
plt.title("FRA Local Soya Bean Price Trend Per Kg (2020–2022)")
plt.grid(True)
plt.show()

"""Price per 50KG Bag"""

plt.figure(figsize=(8,5))
plt.bar(df["Year"], df["Price_per_Bag_50KG"])
plt.xlabel("Year")
plt.ylabel("Price (ZMW per 50KG bag)")
plt.title("FRA 50KG Soya Bean Bag Price (2020–2022)")
plt.show()